logging.level:
  org.springframework.web: INFO
  reactor.netty: INFO
  com.nurkiewicz: DEBUG

emoji-tracker.url: http://emojitrack-gostreamer.herokuapp.com/subscribe/eps
feed-file: "/feed-en.xml"

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  r2dbc:
    username: test
    password: test
    pool:
      enabled: true

